version: '2'
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
- "api/server/src/config/"
- "api/server/src/models/"
- "api/server/src/migrations/"
- "api/server/src/seeders/"
- "api/server/src/helpers/factory"
- "**/node_modules/"
- "templates/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
